sudo: false

language: generic

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/massiv/.stack-work
  - $TRAVIS_BUILD_DIR/massiv-test/.stack-work
  timeout: 360

matrix:
  include:

  - env: GHC="8.4.4" RESOLVER="lts-12.26" STACK_YAML="stack-extra-deps.yaml"
    os: osx

  - env: GHC="8.6.5" RESOLVER="lts-14.27" STACK_YAML="stack-extra-deps.yaml"
    os: osx

  - env: GHC="8.8.3" RESOLVER="lts-16"
    os: osx


  - env: GHC="8.4.3" RESOLVER="lts-12.14" STACK_YAML="stack-extra-deps.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.4.4" RESOLVER="lts-12.26" STACK_YAML="stack-extra-deps.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.6.3" RESOLVER="lts-13.9" STACK_YAML="stack-extra-deps.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.6.4" RESOLVER="lts-13.19" STACK_YAML="stack-extra-deps.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.6.5" RESOLVER="lts-14.27" STACK_YAML="stack-extra-deps.yaml" COVERALLS_STACK_YAML="stack-extra-deps.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.8.4" RESOLVER="lts-16.31"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.10.4" RESOLVER="lts-17"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: RESOLVER="nightly"
    addons: {apt: {packages: [libgmp-dev]}}

  allow_failures:
  - env: RESOLVER="nightly"

before_install:
- |
  travis_retry curl -sSL https://gist.githubusercontent.com/lehins/fd36a8cc8bf853173437b17f6b6426ad/raw/d9ddb32cac2f0dc6800be4fa54d450f0dcda6c60/git-modtime.hs -o git-modtime.hs
  travis_retry curl -sSL https://get.haskellstack.org/ | sh -s - -f
  BUILD_ARGS="--bench --no-run-benchmarks --haddock --no-haddock-deps"
  if [ -n "${COVERALLS_STACK_YAML}" ]; then
     STACK_YAML="${COVERALLS_STACK_YAML}"
     travis_retry curl -L https://github.com/lehins/stack-hpc-coveralls/releases/download/0.0.5.0/shc.tar.gz | tar xz shc
     BUILD_ARGS="${BUILD_ARGS} --coverage"
  fi

script:
- |
  set -ex
  ARGS="--resolver $RESOLVER"
  stack $ARGS script git-modtime.hs
  # ^ ensure file modification timestamp matches the time it was committed.
  stack $ARGS test --no-run-tests $BUILD_ARGS
  # ^ ensure everything else beside test suite gets built as well.
  stack $ARGS test massiv-test:tests $BUILD_ARGS
  if [ -n "${COVERALLS_STACK_YAML}" ]; then
     stack $ARGS hpc report --all
     STACK_YAML="${COVERALLS_STACK_YAML}" ./shc --partial-coverage --fetch-coverage combined custom
  fi
  stack $ARGS test massiv:doctests $BUILD_ARGS
  set -ex
