version: 1.0.{build}
image: Visual Studio 2015

build: off

environment:
  global:
    # Avoid long paths on Windows
    STACK_ROOT: "c:\\s"
    STACK_WORK: ".w"
    WORK_DIR: "c:\\m"
  matrix:
  - ARGS: "--resolver lts-9 --stack-yaml stack-ghc-8.0.yaml"
  - ARGS: "--resolver lts-11 --stack-yaml stack-ghc-8.0.yaml"
  - ARGS: "--resolver lts-12"
  - ARGS: "--resolver lts-13.11" # FIXME (appveyor/ghc-8.6.4 haddock issue?)
  - ARGS: "--resolver nightly"
matrix:
  allow_failures:
    - ARGS: "--resolver nightly"

init:
  - SET WORK_DIR_NO_PR=%WORK_DIR%\%APPVEYOR_REPO_BRANCH%
  - SET STACK_ROOT_NO_PR=%STACK_ROOT%\%APPVEYOR_REPO_BRANCH%
  - SET WORK_DIR=%WORK_DIR%\%APPVEYOR_PULL_REQUEST_NUMBER%\%APPVEYOR_REPO_BRANCH%\
  - SET STACK_ROOT=%STACK_ROOT%\%APPVEYOR_PULL_REQUEST_NUMBER%\%APPVEYOR_REPO_BRANCH%\

cache:
- "%STACK_ROOT_NO_PR%"
- "%WORK_DIR_NO_PR%\\%STACK_WORK%"
- "%LOCALAPPDATA%\\Programs\\stack"

before_test:
# Avoid long paths not to each MAX_PATH of 260 chars
- xcopy /q /s /e /r /k /i /v /h /y C:\projects\massiv "%WORK_DIR%"
- xcopy /q /s /e /r /k /i /v /h /y C:\projects\massiv "%WORK_DIR%"
- cd "%WORK_DIR%"
# Setup cache dirs
# Debug paths
- Echo WORK_DIR = %WORK_DIR%
- dir %WORK_DIR%
- Echo STACK_ROOT = %STACK_ROOT%


# Install stack
- ps: Start-FileDownload http://www.stackage.org/stack/windows-x86_64 -FileName stack.zip
- 7z x stack.zip stack.exe -aoa

test_script:
  - cd "%WORK_DIR%"
  - stack %ARGS% --verbosity warn setup --no-reinstall > nul
  - stack %ARGS% test massiv-scheduler:tests
      -j 2
      --no-terminal
      --haddock
      --no-haddock-deps
  - stack %ARGS% test massiv:tests massiv:doctests
      -j 2
      --flag massiv:unsafe-checks
      --no-terminal
      --haddock
      --no-haddock-deps


notifications:
  - provider: Email
    to:
      - lehins@yandex.ru
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
