version: 1.0.{build}
image: Visual Studio 2015

build: off

environment:
  global:
    # Avoid long paths on Windows
    STACK_ROOT: "c:\\s"
    STACK_WORK: ".w"
    WORK_DIR: "c:\\w"

init:
  - SET WORK_DIR_NO_PR=%WORK_DIR%\%APPVEYOR_REPO_BRANCH%
  - SET STACK_ROOT_NO_PR=%STACK_ROOT%\%APPVEYOR_REPO_BRANCH%
  - SET WORK_DIR=%WORK_DIR%\%APPVEYOR_PULL_REQUEST_NUMBER%\%APPVEYOR_REPO_BRANCH%\
  - SET STACK_ROOT=%STACK_ROOT%\%APPVEYOR_PULL_REQUEST_NUMBER%\%APPVEYOR_REPO_BRANCH%\

cache:
  - "%STACK_ROOT_NO_PR%"
  - "%WORK_DIR_NO_PR%"

before_test:
# Avoid long paths not to each MAX_PATH of 260 chars
- xcopy /q /s /e /r /k /i /v /h /y C:\projects\massiv\massiv "%WORK_DIR%"
- cd "%WORK_DIR%"
# Setup cache dirs
# Debug paths
- Echo WORK_DIR = %WORK_DIR%
- dir %WORK_DIR%
- Echo STACK_ROOT = %STACK_ROOT%


# Install stack
- ps: Start-FileDownload http://www.stackage.org/stack/windows-x86_64 -FileName stack.zip
- 7z x stack.zip stack.exe

test_script:
  - cd "%WORK_DIR%"
  - stack --verbosity warn setup --no-reinstall > nul
  - stack test massiv:tests
      -j 2
      --no-terminal
      --no-haddock-deps
      --work-dir %STACK_WORK%


notifications:
  - provider: Email
    to:
      - lehins@yandex.ru
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
